/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CaiEmUmGolpeRouteImport } from './routes/cai-em-um-golpe'
import { Route as DuvidasRouteImport } from './routes/duvidas'
import { Route as GolpesRouteImport } from './routes/golpes'
import { Route as IniciantesRouteImport } from './routes/iniciantes'
import { Route as ProtegerRouteImport } from './routes/proteger'
import { Route as RedesSociaisRouteImport } from './routes/redes-sociais'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CaiEmUmGolpeRoute = CaiEmUmGolpeRouteImport.update({
  id: '/cai-em-um-golpe',
  path: '/cai-em-um-golpe',
  getParentRoute: () => rootRouteImport,
} as any)
const DuvidasRoute = DuvidasRouteImport.update({
  id: '/duvidas',
  path: '/duvidas',
  getParentRoute: () => rootRouteImport,
} as any)
const GolpesRoute = GolpesRouteImport.update({
  id: '/golpes',
  path: '/golpes',
  getParentRoute: () => rootRouteImport,
} as any)
const IniciantesRoute = IniciantesRouteImport.update({
  id: '/iniciantes',
  path: '/iniciantes',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtegerRoute = ProtegerRouteImport.update({
  id: '/proteger',
  path: '/proteger',
  getParentRoute: () => rootRouteImport,
} as any)
const RedesSociaisRoute = RedesSociaisRouteImport.update({
  id: '/redes-sociais',
  path: '/redes-sociais',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cai-em-um-golpe': typeof CaiEmUmGolpeRoute
  '/duvidas': typeof DuvidasRoute
  '/golpes': typeof GolpesRoute
  '/iniciantes': typeof IniciantesRoute
  '/proteger': typeof ProtegerRoute
  '/redes-sociais': typeof RedesSociaisRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cai-em-um-golpe': typeof CaiEmUmGolpeRoute
  '/duvidas': typeof DuvidasRoute
  '/golpes': typeof GolpesRoute
  '/iniciantes': typeof IniciantesRoute
  '/proteger': typeof ProtegerRoute
  '/redes-sociais': typeof RedesSociaisRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cai-em-um-golpe': typeof CaiEmUmGolpeRoute
  '/duvidas': typeof DuvidasRoute
  '/golpes': typeof GolpesRoute
  '/iniciantes': typeof IniciantesRoute
  '/proteger': typeof ProtegerRoute
  '/redes-sociais': typeof RedesSociaisRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cai-em-um-golpe'
    | '/duvidas'
    | '/golpes'
    | '/iniciantes'
    | '/proteger'
    | '/redes-sociais'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cai-em-um-golpe'
    | '/duvidas'
    | '/golpes'
    | '/iniciantes'
    | '/proteger'
    | '/redes-sociais'
  id:
    | '__root__'
    | '/'
    | '/cai-em-um-golpe'
    | '/duvidas'
    | '/golpes'
    | '/iniciantes'
    | '/proteger'
    | '/redes-sociais'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CaiEmUmGolpeRoute: typeof CaiEmUmGolpeRoute
  DuvidasRoute: typeof DuvidasRoute
  GolpesRoute: typeof GolpesRoute
  IniciantesRoute: typeof IniciantesRoute
  ProtegerRoute: typeof ProtegerRoute
  RedesSociaisRoute: typeof RedesSociaisRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cai-em-um-golpe': {
      id: '/cai-em-um-golpe'
      path: '/cai-em-um-golpe'
      fullPath: '/cai-em-um-golpe'
      preLoaderRoute: typeof CaiEmUmGolpeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/duvidas': {
      id: '/duvidas'
      path: '/duvidas'
      fullPath: '/duvidas'
      preLoaderRoute: typeof DuvidasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/golpes': {
      id: '/golpes'
      path: '/golpes'
      fullPath: '/golpes'
      preLoaderRoute: typeof GolpesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iniciantes': {
      id: '/iniciantes'
      path: '/iniciantes'
      fullPath: '/iniciantes'
      preLoaderRoute: typeof IniciantesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proteger': {
      id: '/proteger'
      path: '/proteger'
      fullPath: '/proteger'
      preLoaderRoute: typeof ProtegerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redes-sociais': {
      id: '/redes-sociais'
      path: '/redes-sociais'
      fullPath: '/redes-sociais'
      preLoaderRoute: typeof RedesSociaisRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CaiEmUmGolpeRoute: CaiEmUmGolpeRoute,
  DuvidasRoute: DuvidasRoute,
  GolpesRoute: GolpesRoute,
  IniciantesRoute: IniciantesRoute,
  ProtegerRoute: ProtegerRoute,
  RedesSociaisRoute: RedesSociaisRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
